WIP - clicking issue on mrjsio
Volumetrics-io/mrjs pull request #497
Opened 2024-03-12 22:43 UTC by hanbollar

## Linking

Fixes https://github.com/Volumetrics-io/mrjs/issues/434
Fixes https://github.com/Volumetrics-io/mrjs/issues/450

## Problem

See the noted issues

## Solution

tbd.

------------

## Required to Merge

- [ ] **PASS** - all necessary actions must pass (excluding the auto-skipped ones)
- [ ] **TEST IN HEADSET** - [main dev-testing-example](https://github.com/Volumetrics-io/mrjs/tree/main/samples/index.html) and any of the other [examples](https://github.com/Volumetrics-io/mrjs/tree/main/samples/examples) still work as expected
- [ ] **VIDEO** - if this pr changes something visually - post a video here of it in headset-MR and/or on desktop (depending on what it affects) for the reviewer to reference.
- [ ] **TITLE** - make sure the pr's title is updated appropriately as it will be used to name the commit on merge
- [ ] **BREAKING CHANGE**
  - make a pr in the [documentation repo](https://github.com/Volumetrics-io/documentation) that updates the manual docs to match the breaking change
  - note: the docs underneath the `Javascript API` section come automated from the jsdocs inline with the code itself
  - link the pr of the documentation repo here: *#pr*
  - that documentation repo pr must be approved by `@lobau`

2024-03-12 22:55 UTC, hanbollar commented
looks like the issue is specific to the rotating colliders and what is closest

since the models are rotating their colliders are coming in the way of that of the objects themself - gonna noodle thru this a bit in relation to if we can grab a specific link versus closest

2024-03-12 23:54 UTC, hanbollar commented
also the model colliders are huge compared to their own size - still looking into why the diff in size expectation

2024-03-14 18:05 UTC, hanbollar commented
additional noodle: part of it is due to resize changing scale of bbox though reload of page fixes it

2024-03-14 23:57 UTC, michaelthatsit commented on src/core/componentSystems/PhysicsSystem.js
> +        this.eventUpdate();
oof nah we can't do it this way. `eventUpdate` is only meant to be called on events, not per frame.

2024-03-15 00:13 UTC, michaelthatsit requested changes
The changes you made in `eventUpdate` & `update` reintroduce performance bugs we resolved a couple weeks ago. Are they absolutely necessary for this fix to work?

2024-03-15 00:22 UTC, hanbollar commented on src/core/componentSystems/PhysicsSystem.js
> -            }
oh these arent required - was trying to simplify the update but if the difference of separation is needed, can still do that 👍

2024-03-15 06:08 UTC, michaelthatsit approved these changes

2024-03-15 16:27 UTC, merged